### ISSUE TITLE
日卡无法激活

### ISSUE THREAD

**Issue by mengqidiluff** [stefanli2577/pxq-dm#2]
订单号: ZDVU最后是XFK7

**Comment by stefanli2577** [comment]
我测试了您的激活码是可以激活的。请尝试下载最新版本软件:票帮帮V2
<https://pxq.pxqdm666.top/%E7%A5%A8%E5%B8%AE%E5%B8%AEV2%28%E6%94%AF%E6%8C%81%E4%BB%A3%E7%90%86%29.zip>

重新发您一个新的激活码为:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5weHFkbTY2Ni50b3AiLCJpYXQiOjE3MTI2NDcxMTYsImV4cCI6MTcyMzAxNTExNiwibmJmIjoxNzEyNjQ3MTE2LCJqdGkiOiJlaTlUc3VQM3hEZ05VUTBpIiwic3ViIjoiMTIwNCIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.1VMGOAX3iEoARdCJbc9sFoRrtrJUGqhE2LRzTRh8LHU

mengqidiluff ***@***.***> 于2024年4月9日周二 12:34写道：

**Comment by stefanli2577** [comment]
> 订单号: ZDVU最后是XFK7

已处理，请查收邮件
