### ISSUE TITLE
今天的杭州周杰伦showid没有用是怎么回事

### ISSUE THREAD

**Issue by BigFrog1010** [stefanli2577/pxq-dm#5]
今天的杭州周杰伦showid没有用是怎么回事

**Comment by stefanli2577** [comment]
票星球没有杭州周杰伦吧[image: image.png]

BigFrog1010 ***@***.***> 于2024年4月12日周五 10:17写道：

**Comment by stefanli2577** [comment]
> 今天的杭州周杰伦showid没有用是怎么回事
下个版本更换APP的API
