### ISSUE TITLE
为什么无法访问激活码购买地址了？

### ISSUE THREAD

**Issue by RainySat** [stefanli2577/pxq-dm#6]
网址为 https://pxqdm666.top/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_ADDRESS_INVALID

是地区问题嘛，我在北京

**Comment by stefanli2577** [comment]
网络问题，应该是DNS。尝试添加DNS: 8.8.8.8

rainysat ***@***.***> 于2024年4月12日周五 10:53写道：

**Comment by RainySat** [comment]
![image](https://github.com/stefanli2577/pxq-dm/assets/8650396/d919dd1f-ae51-4ac7-b489-03db579d43dd)
还是一样，我也换了网络环境，5g也试过，还是无法访问

**Comment by stefanli2577** [comment]
手机也无法访问，有点离谱了

rainysat ***@***.***> 于2024年4月12日周五 12:02写道：

**Comment by stefanli2577** [comment]
网站是套了CDN的

stefan handsome ***@***.***> 于2024年4月12日周五 12:03写道：

**Comment by RainySat** [comment]
挂了个梯子可以进了，那可能cdn在我这个区域有问题

**Comment by stefanli2577** [comment]
> 挂了个梯子可以进了，那可能cdn在我这个区域有问题

CDN已经关了，试试
