### ISSUE TITLE
问下票星球成功率高吗

### ISSUE THREAD

**Issue by jyC23333** [stefanli2577/pxq-dm#7]
问下票星球成功率高吗？
是否支持捡漏？

**Comment by jyC23333** [comment]
请问下有支持linux的软件版本吗

**Comment by stefanli2577** [comment]
票星球概率还行，有时候猫眼大麦卖完的票，票星球还能捡漏。 支持捡漏

jyC233 ***@***.***> 于2024年4月12日周五 12:58写道：
